### ISSUE TITLE
Parameters?

### ISSUE THREAD

**Issue by PrimEverDream** [force-net/Crc32.NET#21]
Hello there,
Maybe I missed something obvious, but I cannot find how you fixed the parameters, nor how I can change those
I don't even know where to find the poly you used and how I can change it if possible

Could you show me where to find those info?
Thanks =)

**Comment by force-net** [comment]
CRC32 has fixed poly. There are no need to change it. If you trying to implement another crc variant, you can look at 
https://github.com/force-net/Crc32.NET/blob/develop/Crc32.NET/SafeProxy.cs#L15
There are poly, which used for CRC32 (reversed)

**Comment by PrimEverDream** [comment]
Thanks a lot for this, I did not know where llok for this =)
