### ISSUE TITLE
Native version to call with dllimport?

### ISSUE THREAD

**Issue by Mrgaton** [force-net/Crc32.NET#24]
I need the fastest way of checking the crc32 of large files so a native version would be great if I could call it with a byte[] or with a file path

**Comment by force-net** [comment]
You can use https://github.com/robertvazan/crc32c-hw/blob/master/crc32c/crc32c.c implementation of crc32c algorithm and change poly for crc32

**Comment by Mrgaton** [comment]
Thanks
