### ISSUE TITLE
Warning on .Net Core 2.0

### ISSUE THREAD

**Issue by majatu** [force-net/Crc32.NET#3]
I have a warning at VS 2017 with 1.1.0 version

Warning	NU1603	Crc32.NET 1.1.0 depends on NETStandard.Library (>= 1.3.0) but NETStandard.Library 1.3.0 was not found. An approximate best match of NETStandard.Library 1.6.0 was resolved.

**Comment by force-net** [comment]
Do you have this problem with packaged version, or you include it as source?

I did not see any warnings when it used as package, but Microsoft is changing building behavior continuously, so I admit, this problem can occur.

I intentionally has added reference to version of NETStandard.Library that lower than existing but has not think that it can affect somebody except me.

**Comment by majatu** [comment]
As a nuget package. I'm using it on core 2.0.

**Comment by force-net** [comment]
Ok. I'll try to find and eliminate this issue, and also add .NET Core 2.0 version if it differs by API from .NET Core 1.3

**Comment by majatu** [comment]
Thank you
